### ISSUE TITLE
Ability to export Babylon.js compatible .bin file

### ISSUE THREAD

**Issue by EricEisaman** [przemir/RecastBlenderAddon#1]
Hello @przemir .   Would it take much to build in the ability to export a Babylon.js compatible .bin file representing the navmesh?

**Comment by przemir** [comment]
Hello. I didn't work with Babylon.js so I don't really know about that. But maybe blender exporter addon will be enough? Like something like here: https://github.com/BabylonJS/BlenderExporter ?

**Comment by EricEisaman** [comment]
Thanks @przemir. I will look into it. Have a great day!
